// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xreaohljluklekyolwfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZWFvaGxqbHVrbGVreW9sd2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Njg4ODMsImV4cCI6MjA3MjE0NDg4M30.xEtaPtVVwi1x-EKPWTQ0AgPNES3oGaYf3VZSRJsAeFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});